var b=null,g;function h(){this.k=document.createElement("aside");this.k.className="msModal";this.k.id="mask";this.k.style.display="none";this.$=document.createElement("div");this.$.innerHTML="";this.k.appendChild(this.$);document.body.appendChild(this.k)}
h.prototype.show=function(a){var c=document.getElementsByClassName("container"),d=c.length;if(c!=b&&d!=0)for(var e=0;e<d;e++)c.item(e).blur();if(document.getElementById("menuSearchByText")!=b&&document.getElementById("menuSearchMyFav")!=b){c=document.getElementsByTagName("a");for(d=0;d<c.length;d++)c[d].blur()}this.$.innerHTML=a;this.k.style.display="inline-block"};h.prototype.hide=function(){this.k.style.display="none"};h.prototype.$a=function(){return this.k.style.display=="none"?!1:!0};
window.maskPanel=h;window.maskPanel.prototype.hide=h.prototype.hide;window.maskPanel.prototype.show=h.prototype.show;window.maskPanel.prototype.isVisible=h.prototype.$a;var i,j={a:{O:65,N:81,Ma:403,Fa:404,Qa:405,Ca:406,Ga:74,z:82,Ka:415,Ja:19,Oa:413,Ea:417,Da:412,Ia:113,La:112,Ra:461,Ha:457,Pa:0,oa:48,qa:49,ra:50,ua:51,va:52,xa:53,ya:54,za:55,Aa:56,Ba:57,m:37,n:39,o:38,l:40,Na:13},w:{M:2E4,L:1024E3}},m={a:{O:61510,N:61511,Ma:403,Fa:404,Qa:502,Ca:406,Ga:62720,z:461,Ka:61521,Ja:61450,Oa:61522,Ea:61530,Da:61529,Ia:61532,La:61531,Ra:0,Ha:61460,Pa:0,oa:48,qa:49,ra:50,ua:51,va:52,xa:53,ya:54,za:55,Aa:56,Ba:57,m:37,n:39,o:38,l:40,Na:13},w:{M:2E4,L:1024E3}},n={a:{O:77,N:78,
Ma:81,Fa:87,Qa:69,Ca:82,Ga:72,z:66,Ka:65,Ja:83,Oa:68,Ea:86,Da:67,Ia:88,La:90,Ra:70,Ha:73,Pa:84,oa:48,qa:49,ra:50,ua:51,va:52,xa:53,ya:54,za:55,Aa:56,Ba:57,m:37,n:39,o:38,l:40,Na:13},w:{M:2E4,L:1024E3}};i=navigator.appVersion.search("OWB")!=-1?j:navigator.appVersion.search("mips")!=-1?m:n;function p(a,c){this.sb=a;this.tb=c};var q=[];q.ab="Abkhazian";q.aa="Afar";q.af="Afrikaans";q.sq="Albanian";q.am="Amharic";q.ar="Arabic";q.an="Aragonese";q.hy="Armenian";q.as="Assamese";q.ay="Aymara";q.az="Azerbaijani";q.ba="Bashkir";q.eu="Basque";q.bn="Bengali (Bangla)";q.dz="Bhutani";q.bh="Bihari";q.bi="Bislama";q.br="Breton";q.bg="Bulgarian";q.my="Burmese";q.be="Byelorussian (Belarusian)";q.km="Cambodian";q.ca="Catalan";q.zh="Chinese (Simplified)";q.zh="Chinese (Traditional)";q.co="Corsican";q.hr="Croatian";q.cs="Czech";q.da="Danish";
q.nl="Dutch";q.en="English";q.eo="Esperanto";q.et="Estonian";q.fo="Faeroese";q.fa="Farsi";q.fj="Fiji";q.fi="Finnish";q.fr="French";q.fy="Frisian";q.gl="Galician";q.gd="Gaelic (Scottish)";q.gv="Gaelic (Manx)";q.ka="Georgian";q.de="German";q.el="Greek";q.kl="Greenlandic";q.gn="Guarani";q.gu="Gujarati";q.ht="Haitian Creole";q.ha="Hausa";q.he="Hebrew";q.hi="Hindi";q.hu="Hungarian";q.is="Icelandic";q.io="Ido";q.id="Indonesian";q.ia="Interlingua";q.ie="Interlingue";q.iu="Inuktitut";q.ik="Inupiak";
q.ga="Irish";q.it="Italian";q.ja="Japanese";q.jv="Javanese";q.kn="Kannada";q.ks="Kashmiri";q.kk="Kazakh";q.rw="Kinyarwanda (Ruanda)";q.ky="Kirghiz";q.rn="Kirundi (Rundi)";q.ko="Korean";q.ku="Kurdish";q.lo="Laothian";q.la="Latin";q.lv="Latvian (Lettish)";q.li="Limburgish ( Limburger)";q.ln="Lingala";q.lt="Lithuanian";q.mk="Macedonian";q.mg="Malagasy";q.ms="Malay";q.ml="Malayalam";q.mt="Maltese";q.mi="Maori";q.mr="Marathi";q.mo="Moldavian";q.mn="Mongolian";q.na="Nauru";q.ne="Nepali";q.no="Norwegian";
q.oc="Occitan";q.or="Oriya";q.om="Oromo (Afaan Oromo)";q.ps="Pashto (Pushto)";q.pl="Polish";q.pt="Portuguese";q.pa="Punjabi";q.qu="Quechua";q.rm="Rhaeto-Romance";q.ro="Romanian";q.ru="Russian";q.sm="Samoan";q.sg="Sangro";q.sa="Sanskrit";q.sr="Serbian";q.sh="Serbo-Croatian";q.st="Sesotho";q.tn="Setswana";q.sn="Shona";q.ii="Sichuan Yi";q.sd="Sindhi";q.si="Sinhalese";q.ss="Siswati";q.sk="Slovak";q.sl="Slovenian";q.so="Somali";q.es="Spanish";q.su="Sundanese";q.sw="Swahili (Kiswahili)";q.sv="Swedish";
q.tl="Tagalog";q.tg="Tajik";q.ta="Tamil";q.tt="Tatar";q.te="Telugu";q.th="Thai";q.bo="Tibetan";q.ti="Tigrinya";q.to="Tonga";q.ts="Tsonga";q.tr="Turkish";q.tk="Turkmen";q.tw="Twi";q.ug="Uighur";q.uk="Ukrainian";q.ur="Urdu";q.uz="Uzbek";q.vi="Vietnamese";q.vo="Volap\u00fck";q.wa="Wallon";q.cy="Welsh";q.wo="Wolof";q.xh="Xhosa";q.yi="Yiddish";q.yo="Yoruba";q.zu="Zulu";function s(){this.xhr=new XMLHttpRequest;this.maxLength=i.w.L;this.ob=i.w.M;this.ma=!0;this.ub="";typeof u=="undefined"?u=1:u+=1}var u;(function(a,c){function d(){}d.prototype=c.prototype;a.prototype=new d})(s,XMLHttpRequest);g=s.prototype;g.readyState={mb:0,lb:1,kb:2,LOADING:3,DONE:4};
g.status={Ab:100,ec:101,Tb:200,Bb:201,wb:202,Nb:203,Sb:204,bc:205,Ub:206,Mb:300,Lb:301,Eb:302,cc:303,Rb:304,ic:305,fc:307,yb:400,gc:401,Vb:402,Db:403,Pb:404,Kb:405,Ob:406,Xb:407,$b:408,zb:409,Gb:410,Jb:411,Wb:412,Zb:413,ac:414,hc:415,Yb:416,Cb:417,Ib:500,Qb:501,xb:502,dc:503,Fb:504,Hb:505};
g.open=function(a,c,d){var e=this;this.xhr.onreadystatechange=function(){if(e.Sa!=!0){var a;try{e.xhr.getResponseHeader("Content-Length")&&(a=parseInt(e.xhr.getResponseHeader("Content-Length"),10))}catch(c){a=0}if(a>e.maxLength)e.Sa=!0,e.xhr.abort(),window.clearTimeout(e.fb),u-=1,u==0&&(window.maskPanel.show("<div id='id_mask_abort_error'><div id='id_mask_abort_img'></div><div id='id_str_network_abort_text'></div></div>"),setTimeout("maskPanel.hide();",3E3));if(e.xhr.readyState!=e.readyState.mb&&
e.xhr.readyState!=e.readyState.lb&&e.xhr.readyState!=e.readyState.kb&&e.xhr.readyState!=e.readyState.LOADING&&e.xhr.readyState==e.readyState.DONE)if(window.clearTimeout(e.fb),u-=1,e.xhr.status==200)if(e.onreadystatechange(e.xhr.responseText),u==0&&e.ma)u==0&&window.maskPanel.hide();else{if(!e.ma)e.ma=!0}else e.xhr.status==400?u==0&&(window.maskPanel.show("<div id='id_mask_abort_error'><div id='id_mask_abort_img'></div><div id='id_str_network_abort_text'></div></div>"),setTimeout("maskPanel.hide();",
3E3)):u==0&&(window.maskPanel.show("<div id='id_mask_load_error'><div id='id_mask_error_img'></div><div id='id_str_network_error_text'></div></div>"),setTimeout("maskPanel.hide();",3E3))}};this.xhr.open(a,c,d)};
g.send=function(a){u==1&&window.maskPanel.show("<div id='id_mask_loading'><div id='id_mask_loading_img'></div><div id='id_str_network_loading_text'>"+this.ub+"</div></div>");this.Sa=!1;this.xhr.send(a);var c=this;this.fb=window.setTimeout(function(){c.xhr.abort();u==0&&(window.maskPanel.show("<div id='id_mask_load_timeout'><div id='id_mask_timeout_img'></div><div id='id_str_network_timeout_text'></div></div>"),setTimeout("maskPanel.hide();",3E3))},this.ob)};g.getResponseHeader=function(a){return this.xhr.getResponseHeader(a)};
g.abort=function(){};g.onreadystatechange=function(){alert("ERROR => Must be override")};function v(a,c,d,e,f,l,o){this.pb=a;this.content=c;this.f=d;this.e=e;this.cb=o;this.Wa=f;this.jb=l;this.initialize()}
v.prototype.initialize=function(){this.S=!0;this.T=!1;this.V=!0;this.U=!1;for(var a=["a","input","object"],c=0;c<a.length;c++)for(var d=this.content.getElementsByTagName(a[c]),e=d.length-1;e>=0;e--){var f=document.createElement("span");f.innerHTML=d[e].innerHTML;d[e].parentNode.replaceChild(f,d[e])}this.d=this.content.id;this.nb="scrollAllContainerfor"+this.d;this.D="horizontalScrollfor"+this.d;this.J="verticalScrollfor"+this.d;this.jc=this.eb=0.025;this.qb="scrollContentStylefor"+this.d;this.Za=
"horizontalScrollStyleContainerfor"+this.d;this.ib="verticalScrollStyleContainerfor"+this.d;this.F=this.f*this.eb;this.K=this.e*this.eb;this.j=!1;a=document.createElement("div");a.style.position="relative";a.style.cssFloat="left";a.style.width=this.f+"px";a.style.height=this.e+"px";a.style.overflow="hidden";this.Ua=a;a=document.createElement("div");a.setAttribute("id",this.qb);this.Va=a;this.Ua.appendChild(this.content);this.Va.appendChild(this.Ua);a=document.createElement("div");a.setAttribute("id",
this.D);a.style.position="relative";a.style.cssFloat="left";a.style.width="0px";a.style.height=this.Wa+"px";a.style.marginLeft="0px";a.style.backgroundColor=this.cb;this.rb=a;a=document.createElement("div");a.style.position="relative";a.style.cssFloat="left";a.style.width=this.f+"px";a.style.height=this.Wa+"px";this.Xa=a;a=document.createElement("div");a.setAttribute("id",this.Za);this.Ya=a;this.Xa.appendChild(this.rb);this.Ya.appendChild(this.Xa);a=document.createElement("div");a.setAttribute("id",
this.J);a.style.position="relative";a.style.cssFloat="left";a.style.width=this.jb+"px";a.style.height="0px";a.style.marginTop="0px";a.style.backgroundColor=this.cb;this.vb=a;a=document.createElement("div");a.style.position="relative";a.style.cssFloat="left";a.style.width=this.jb+"px";a.style.height=this.e+"px";this.gb=a;a=document.createElement("div");a.setAttribute("id",this.ib);this.hb=a;this.gb.appendChild(this.vb);this.hb.appendChild(this.gb);this.t=w(this);this.t.appendChild(this.Va);this.t.appendChild(this.hb);
this.t.appendChild(this.Ya);this.pb.appendChild(this.t);a=document.getElementById(this.d);this.B=x(a,!1);this.A=x(this.content,!0);a.style.marginTop="0px";a.style.marginLeft="0px";this.q=this.f>=this.B?!1:!0;a=document.getElementById(this.D);this.q?this.G=this.f*this.f/this.B:(this.G=this.f,document.getElementById(this.Za).style.display="none");a.style.width=this.G+"px";this.s=this.e>=this.A?!1:!0;a=document.getElementById(this.J);this.s?this.I=this.e*this.e/this.A:(this.I=this.e,document.getElementById(this.ib).style.display=
"none");a.style.height=this.I+"px";this.focus()};v.prototype.focus=function(){this.t.focus()};function w(a){var c;c=document.createElement("a");c.setAttribute("id",a.nb);c.setAttribute("href","#");c.style.textDecoration="none";c.addEventListener("focus",function(){a.j=!0},!1);c.addEventListener("blur",function(){a.j=!1},!1);return c}
v.prototype.h=function(a){if(this.j){switch(a.keyCode){case i.a.m:if(this.q){this.T=this.S=!1;var c=document.getElementById(this.d),d=document.getElementById(this.D),e=parseFloat(c.style.marginLeft)+this.F,f=parseFloat(d.style.marginLeft)-(this.f-this.G)/((this.B-this.f)/this.F);if(f<=0)this.S=!0,f=e=0;c.style.marginLeft=e+"px";d.style.marginLeft=f+"px"}break;case i.a.n:if(this.q){this.T=this.S=!1;var c=document.getElementById(this.d),d=document.getElementById(this.D),e=x(c,!1),f=x(c.parentNode,!1),
l=x(d,!1),o=x(d.parentNode,!1),k=parseFloat(c.style.marginLeft)-this.F,r=parseFloat(d.style.marginLeft)+(this.f-this.G)/((this.B-this.f)/this.F);if(l+r>=o)this.T=!0,k=f-e,r=o-l;c.style.marginLeft=k+"px";d.style.marginLeft=r+"px"}break;case i.a.o:if(this.s){this.U=this.V=!1;c=document.getElementById(this.d);d=document.getElementById(this.J);e=parseFloat(c.style.marginTop)+this.K;f=parseFloat(d.style.marginTop)-(this.e-this.I)/((this.A-this.e)/this.K);if(f<=0)this.V=!0,f=e=0;c.style.marginTop=e+"px";
d.style.marginTop=f+"px"}break;case i.a.l:if(this.s){this.U=this.V=!1;c=document.getElementById(this.d);d=document.getElementById(this.J);e=x(c,!0);f=x(c.parentNode,!0);l=x(d,!0);o=x(d.parentNode,!0);k=parseFloat(c.style.marginTop)-this.K;r=parseFloat(d.style.marginTop)+(this.e-this.I)/((this.A-this.e)/this.K);if(l+r>=o)this.U=!0,k=f-e,r=o-l;c.style.marginTop=k+"px";d.style.marginTop=r+"px"}}((a.keyCode==i.a.m||a.keyCode==i.a.n)&&this.q||(a.keyCode==i.a.o||a.keyCode==i.a.l)&&this.s)&&a.preventDefault()}};
function x(a,c){var d=a.ownerDocument&&a.ownerDocument.defaultView&&a.ownerDocument.defaultView.getComputedStyle&&a.ownerDocument.defaultView.getComputedStyle(a,b),e=d&&d.getPropertyValue(c?"height":"width")||"";return e=e&&e.indexOf(".")>-1?parseFloat(e)+parseInt(d.getPropertyValue(c?"padding-top":"padding-left"),10)+parseInt(d.getPropertyValue(c?"padding-bottom":"padding-right"),10)+parseInt(d.getPropertyValue(c?"border-top-width":"border-left-width"),10)+parseInt(d.getPropertyValue(c?"border-bottom-width":
"border-right-width"),10):c?a.offsetHeight:a.offsetWidth};function y(){}function z(a,c,d){var e=new s;if(c!=b&&c.length>0){a+="?";for(var f=0;f<c.length;f++)a=a+c[f].sb+"="+c[f].tb,f!=c.length-1&&(a+="&")}e.open("GET",a,!0);e.onreadystatechange=function(a){d.Ta(a)};e.send()}
y.prototype.search=function(a,c,d,e,f,l,o,k,r){var t=[];c!=""&&t.push(new p("action",c));d!=""&&t.push(new p("prop",d));e!=""&&(c=new p("titles",e.replace(" ","%20")),t.push(c));f!=""&&t.push(new p("rvprop",f));l!=""&&t.push(new p("format",l));o!=""&&t.push(new p("rvparse",o));k!=""&&t.push(new p("rvsection",k));z("http://"+a.toLowerCase()+".wikipedia.org/w/api.php",t,r)};
y.prototype.C=function(a,c,d,e,f,l,o){var k=[];c!=""&&k.push(new p("action",c));d!=""&&(c=new p("titles",d.replace(" ","%20")),k.push(c));e!=""&&k.push(new p("prop",e));f!=""&&k.push(new p("format",f));l!=""&&k.push(new p("llcontinue",l));z("http://"+a.toLowerCase()+".wikipedia.org/w/api.php",k,o)};var A;function B(){this.p=this.c=b;this.bb=new y;C()}function C(){var a=document.getElementById("wikipediaConstantMenuDiv");a.innerHTML="";var c=D("a","wikipediaConstantMenuItem","searchLink","#","");c.addEventListener("click",function(){E(A,1)},!0);a.appendChild(c);c=D("a","wikipediaConstantMenuItem","languageLink","#","");c.addEventListener("click",function(){E(A,2)},!0);a.appendChild(c);c.style.background="url(img/flags/tr.png) no-repeat center";document.getElementById("searchLink").focus()}
function E(a,c){switch(c){case 1:a.c=new F;break;case 2:if(!a.c.g){E(a,1);break}a.p=new G}}function D(a,c,d,e,f){a=document.createElement(a);c!=""&&a.setAttribute("class",c);d!=""&&a.setAttribute("id",d);e!=""&&a.setAttribute("href",e);a.innerHTML=f;return a}function F(){this.i="";this.r=0;this.u="tr";this.H=this.g=!1;this.b=b;this.Y()}
function H(a){a.i="";a.r=0;a.g=!1;a.H=!1;a.b=b;document.getElementById("wikipediaHeaderDiv").innerHTML="";var a=document.getElementById("wikipediaMainContainerDiv"),c=document.getElementById("pageContentDiv");c!=b&&a.removeChild(c);c=document.getElementById("wikipediaSearchContainerDiv");c!=b&&a.removeChild(c);A.p=b}g=F.prototype;g.search=function(){this.i!=""&&A.bb.search(this.u,"query","revisions",this.i,"content","xml","1",this.r.toString(),this)};
g.Ta=function(a){this.g=!0;document.getElementById("wikipediaHeaderDiv").innerHTML=this.i;var c=document.getElementById("wikipediaMainContainerDiv"),d=document.getElementById("wikipediaSearchContainerDiv");d!=b&&c.removeChild(d);d=document.getElementById("pageContentDiv");d!=b&&c.removeChild(d);d=D("div","","pageContentDiv","","");c.appendChild(d);a=(new DOMParser).parseFromString(a,"text/xml");if(a.getElementsByTagName("error").length>0)a="ERROR";else if(a.getElementsByTagName("page")[0].getAttribute("missing")!=
b)a="";else a:{a=a.getElementsByTagName("revisions")[0];if(a!=b)for(a=a.firstChild;a;){if(a.nodeName=="rev"&&a.childNodes[0]!=void 0&&a.childNodes[0].nodeValue!=void 0){a=a.childNodes[0].nodeValue;break a}a=a.nextSibling}a=""}if(a=="ERROR")this.H=!0,document.getElementById("pageContentDiv").innerHTML="END OF THE PAGE";else if(a=="")this.r--,document.getElementById("pageContentDiv").innerHTML="NO CONTENT TO SHOW";else{c=document.createElement("div");c.setAttribute("id","wikipediaSearchedTitleContent");
c.innerHTML=a;this.b=new v(d,c,950,600,20,20,"black");a=this.b.content;c=a.getElementsByTagName("img");for(d=0;d<c.length;d++){var e=c[d].getAttribute("src").toString(),e="http:"+e;c[d].setAttribute("src",e)}a=a.getElementsByClassName("editsection");for(d=0;d<a.length;d++)a[d].parentNode.removeChild(a[d])}};
g.h=function(a){this.b.j&&this.b.h(a);switch(a.keyCode){case i.a.z:this.P();break;case i.a.o:this.ea(a);break;case i.a.l:this.Q(a);break;case i.a.m:this.W(a);break;case i.a.n:this.Z(a);break;case i.a.O:this.g&&!this.H&&(this.r++,this.search());break;case i.a.N:if(this.g&&this.r!=0)this.r--,this.H=!1,this.search()}};g.P=function(){};g.ea=function(a){this.g&&this.b.j&&(this.b.s?this.b.h(a):(document.getElementById("searchLink").focus(),a.preventDefault()))};
g.Q=function(a){this.g&&this.b.j&&(this.b.s?this.b.h(a):(document.getElementById("languageLink").focus(),a.preventDefault()))};g.W=function(a){this.g&&(this.b.j?this.b.q?this.b.h(a):(document.getElementById("searchLink").focus(),a.preventDefault()):this.b.focus())};g.Z=function(a){this.g&&(this.b.j?this.b.q?this.b.h(a):(document.getElementById("languageLink").focus(),a.preventDefault()):this.b.focus())};
g.Y=function(){H(this);document.getElementById("wikipediaHeaderDiv").innerHTML="Search...";var a=document.getElementById("wikipediaMainContainerDiv"),c=D("div","","wikipediaSearchContainerDiv","","");a.appendChild(c);a=D("div","","wikipediaSearchStringDiv","","Find on Wikipedia...");c.appendChild(a);a=D("input","","wikipediaSearchBox","","");a.setAttribute("type","text");c.appendChild(a);var d=D("a","","wikipediaSearchButton","#","Search");d.addEventListener("click",function(){A.c.i=document.getElementById("wikipediaSearchBox").value;
A.c.search()},!0);c.appendChild(d);a.focus()};function G(){this.X="";this.v=[];this.R=!1;A.c.i!=""&&this.C()}g=G.prototype;g.C=function(){A.bb.C("tr","query",A.c.i,"langlinks","xml",this.X,this)};
g.Ta=function(a){var c=(new DOMParser).parseFromString(a,"text/xml").getElementsByTagName("query-continue");if(c.length>0)var d=c[0].getElementsByTagName("langlinks")[0].getAttribute("llcontinue");this.X=d==void 0?"":d;c=[];a=(new DOMParser).parseFromString(a,"text/xml").getElementsByTagName("ll");for(d=0;d<a.length;d++){var e=a[d].getAttribute("lang");c.push(e)}for(a=0;a<c.length;a++)this.v.push(c[a]);this.X==""?this.Y():this.C()};
g.h=function(a){switch(a.keyCode){case i.a.z:this.P();break;case i.a.o:this.ea();a.preventDefault();break;case i.a.l:this.Q();a.preventDefault();break;case i.a.m:this.W();a.preventDefault();break;case i.a.n:this.Z(),a.preventDefault()}};g.P=function(){I(this)};g.ea=function(){};g.Q=function(){};g.W=function(){var a=document.getElementById("langPopUp"),c=a.childNodes;if(c.length!=0){var d=c[c.length-1];a.removeChild(d);a.insertBefore(d,c[0]);document.getElementById("langPopUp").firstChild.focus()}};
g.Z=function(){var a=document.getElementById("langPopUp"),c=a.childNodes;c.length!=0&&(c=c[0],a.removeChild(c),a.appendChild(c),document.getElementById("langPopUp").firstChild.focus())};
g.Y=function(){var a=D("div","","langPopUp","","");document.getElementsByTagName("body")[0].appendChild(a);var c=document.getElementById("languageLink"),d,e=0;d=c.offsetLeft;e=c.offsetTop;for(c=c.offsetParent;c!=b;)d=parseInt(d,10)+parseInt(c.offsetLeft,10),e=parseInt(e,10)+parseInt(c.offsetTop,10),c=c.offsetParent;c=[];c.push(e);c.push(d);a.style.top=(c[0]+18).toString()+"px";a.style.left=(c[1]+2).toString()+"px";J(A.c.u);for(d=0;d<this.v.length;d++)this.v[d]==A.c.u||this.v[d]=="tr"||J(this.v[d]);
A.c.u!="tr"&&J("tr");a.firstChild!=void 0&&a.firstChild.focus();this.R=!0};
function J(a){var c=D("a","langlink","langlink_"+a,"#","");c.addEventListener("click",function(){I(A.p);document.getElementById("languageLink").style.background="url(img/flags/"+a+".png) no-repeat center";var c=A.c,d=c.i;H(c);c.i=d;c.u=a;c.search()},"true");var d="",d=q[a]!=b?q[a]:a,d=D("div","langlinkFlag","langlinkFlag_"+a,"",d);d.style.background="url(img/flags/"+a+".png) no-repeat center";c.appendChild(d);document.getElementById("langPopUp").appendChild(c)}
function I(a){document.getElementsByTagName("body")[0].removeChild(document.getElementById("langPopUp"));a.R=!1}window.init=function(){window.maskPanel=new h;A=new B;E(A,1);window.onkeydown=function(a){window.maskPanel.$a()?(a.preventDefault(),a.stopPropagation()):A.p!=b&&A.p.R?A.p.h(a):A.c.h(a)}};
